name: Build and Deploy Docker Image

on:
  push:
    branches: [ "add-workflow" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./go/
        file: ./go/Dockerfile
        tags: cursproject:latest
        push: false

    - name: Run Docker container
      run: |
        docker run -d -p 8888:8888 cursproject:latest
